version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: MYPROJECTAPI 
      POSTGRES_PASSWORD: MYPROJECT_FORNECEDOR_2023
      POSTGRES_DB: MYPROJECTfornecedordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
