[build]
builder = "NIXPACKS"
buildCommand = "npm run build && npx prisma migrate deploy"

[deploy]
numReplicas = 1
startCommand = "npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
port = 3000